import type { TrackSelectCollection, TrackSelectTrack } from "@weng-lab/genomebrowser-ui";
import mohdAtacData from "./data/mohdAtac.json";
import mohdRnaData from "./data/mohdRna.json";
import mohdWgbsData from "./data/mohdWgbs.json";

/**
 * MOHD track catalog.
 *
 * Genome Browser v1 shipped this catalog inside `@weng-lab/genomebrowser-ui`
 * (as `foldersByAssembly`). v2 made TrackSelect generic, so MOHD now owns its
 * own catalog and builds the collection the dialog consumes.
 *
 * The JSON under ./data is generated by scripts/buildMohdCatalog.mjs from the
 * published file manifests. It stores one row per SAMPLE plus the file set the
 * ome shares, because every per-file column in the manifest is derivable from
 * the sample ID and the file suffix. See that script for the invariants it
 * asserts.
 */

export const MOHD_BASE_URL = "https://downloads.mohdconsortium.org";
export const MOHD_COLLECTION_ID = "human-mohd";

const MOHD_OME_CONFIG = {
  atac: { label: "ATAC", color: "#02c7b9" },
  rna: { label: "RNA", color: "#00aa00" },
  wgbs: { label: "WGBS", color: "#648bd8" },
} as const;

type MohdRawOme = keyof typeof MOHD_OME_CONFIG;

export type MohdOme = (typeof MOHD_OME_CONFIG)[MohdRawOme]["label"];

/** One published file, shared by every sample in the ome. */
type MohdFileSpec = {
  /** Filename after the sample ID, e.g. "signal-FC_GRCh38_v0.bigWig". */
  suffix: string;
  fileType: string;
};

type MohdSample = {
  id: string;
  sex: string;
  site: string;
  status: string;
  /** ATAC only — the assay's sample-preparation method. */
  protocol?: string;
};

type MohdOmeData = {
  ome: string;
  downloadPath: string;
  files: MohdFileSpec[];
  samples: MohdSample[];
};

const MOHD_OME_DATA: MohdOmeData[] = [mohdAtacData, mohdRnaData, mohdWgbsData];

/**
 * Order files are listed in within a sample. The generated JSON is sorted by
 * suffix so the file set compares order-independently; this restores the
 * reading order the omes are normally presented in. Unlisted files follow,
 * keeping their alphabetical order.
 */
const FILE_DISPLAY_ORDER: Record<MohdRawOme, readonly string[]> = {
  atac: ["peaks-FDR5", "peaks-pseudorep", "signal-FC", "signal-pvalue"],
  rna: ["signal-plus-all", "signal-plus-unique", "signal-minus-all", "signal-minus-unique"],
  wgbs: [],
};

/** Sort/grouping facts about a built track, keyed by its qualified track ID. */
export type MohdTrackInfo = {
  id: string;
  ome: MohdOme;
  site: string;
  sampleId: string;
  protocol?: string;
  sex: string;
  status: string;
  description: string;
  trackCategory: "Signal" | "Annotation" | "Methylation";
  /** Position of this file within its ome's display order, for host-side sorting. */
  fileRank: number;
};

const WGBS_DESCRIPTION = "DNA methylation (CpG) and coverage";

/** Track defaults carried over from the v1 folder definitions. */
const BIGWIG_DEFAULTS = { display: "full", height: 30 } as const;
const BIGBED_DEFAULTS = { display: "dense", height: 20 } as const;

/**
 * MOHD's bigBed files are MACS3 narrowPeak (BED6+4), so columns 7-10 are
 * signalValue, pValue, qValue, and the summit offset.
 *
 * The module's default schema is bed9, which reads columns 7-9 as thickStart,
 * thickEnd, and itemRgb. The first two coerce from the float values without
 * complaint, but qValue then fails itemRgb's `R,G,B` pattern and the track
 * renders a validation error in place of its peaks. Parsing as bed6 stops at
 * strand and leaves the four peak columns in `BigBedRow.fields`.
 *
 * The files are written as `bed3+7` (definedFieldCount 3, no narrowPeak
 * autoSql), so nothing in the header identifies the layout — it has to be
 * stated here.
 */
const BIGBED_SCHEMA = "bed6";
/**
 * Half of v1's 75px: this release publishes CpG and coverage only, so each
 * strand renders two channel rows rather than four.
 */
const METHYLC_DEFAULTS = { display: "split", height: 50, color: "#648bd8" } as const;
const METHYLC_COLORS = { cpg: "#648bd8", chg: "#ff944d", chh: "#ff00ff", depth: "#525252" } as const;

/**
 * Filename marker identifying each MethylC channel. CHG and CHH are not part of
 * this release; their lookups find nothing and the channel is disabled, which
 * the module handles without issuing a request. Reinstating those files is
 * therefore a data-only change.
 */
const METHYLC_CHANNEL_MARKERS = {
  plusStrand: { cpg: "DNAme-CpG-plus", chg: "DNAme-CHG-plus", chh: "DNAme-CHH-plus", depth: "coverage-plus" },
  minusStrand: { cpg: "DNAme-CpG-minus", chg: "DNAme-CHG-minus", chh: "DNAme-CHH-minus", depth: "coverage-minus" },
} as const;

function getMohdOmeConfig(rawOme: string) {
  const config = MOHD_OME_CONFIG[rawOme as MohdRawOme];

  if (!config) {
    throw new Error(`Unknown MOHD ome: ${rawOme}`);
  }

  return config;
}

/** Qualified ID that TrackSelect and the track store use: `${collectionId}::${trackId}`. */
export function qualifyMohdTrackId(trackId: string) {
  return `${MOHD_COLLECTION_ID}::${trackId}`;
}

function orderFiles(rawOme: string, files: readonly MohdFileSpec[]) {
  const order = FILE_DISPLAY_ORDER[rawOme as MohdRawOme] ?? [];
  const rankOf = (file: MohdFileSpec) => {
    const index = order.findIndex((prefix) => file.suffix.startsWith(prefix));
    return index === -1 ? order.length : index;
  };

  return [...files].sort((a, b) => rankOf(a) - rankOf(b) || a.suffix.localeCompare(b.suffix));
}

function toMetadata(info: MohdTrackInfo) {
  return {
    ome: info.ome,
    site: info.site,
    sampleId: info.sampleId,
    protocol: info.protocol ?? null,
    sex: info.sex,
    status: info.status,
    description: info.description,
    trackCategory: info.trackCategory,
  };
}

function createFileTrack(
  data: MohdOmeData,
  sample: MohdSample,
  file: MohdFileSpec,
  fileRank: number
): { track: TrackSelectTrack; info: MohdTrackInfo } {
  const { color, label } = getMohdOmeConfig(data.ome);
  const filename = `${sample.id}_${file.suffix}`;
  const isAnnotation = file.suffix.endsWith(".bigBed");
  const trackId = `${sample.id}::${filename}`;

  const info: MohdTrackInfo = {
    id: qualifyMohdTrackId(trackId),
    ome: label,
    site: sample.site,
    sampleId: sample.id,
    protocol: sample.protocol,
    sex: sample.sex,
    status: sample.status,
    description: file.fileType,
    trackCategory: isAnnotation ? "Annotation" : "Signal",
    fileRank,
  };

  return {
    info,
    track: {
      ...(isAnnotation ? BIGBED_DEFAULTS : BIGWIG_DEFAULTS),
      type: isAnnotation ? "bigbed" : "bigwig",
      id: trackId,
      title: `${sample.id} ${file.fileType}`,
      color,
      config: {
        url: `${MOHD_BASE_URL}/${data.downloadPath}/${sample.id}/${filename}`,
        ...(isAnnotation ? { bedSchema: BIGBED_SCHEMA } : {}),
      },
      metadata: toMetadata(info),
    },
  };
}

/**
 * WGBS files are grouped per sample: one MethylC track covers both strands
 * across every published context plus coverage.
 */
function createWgbsMethylTrack(
  data: MohdOmeData,
  sample: MohdSample
): { track: TrackSelectTrack; info: MohdTrackInfo } {
  const channelUrl = (marker: string) => {
    const file = data.files.find((candidate) => candidate.suffix.startsWith(marker));
    return { url: file ? `${MOHD_BASE_URL}/${data.downloadPath}/${sample.id}/${sample.id}_${file.suffix}` : "" };
  };

  const info: MohdTrackInfo = {
    id: qualifyMohdTrackId(sample.id),
    ome: getMohdOmeConfig(data.ome).label,
    site: sample.site,
    sampleId: sample.id,
    protocol: sample.protocol,
    sex: sample.sex,
    status: sample.status,
    description: WGBS_DESCRIPTION,
    trackCategory: "Methylation",
    fileRank: 0,
  };

  return {
    info,
    track: {
      ...METHYLC_DEFAULTS,
      type: "methylc",
      id: sample.id,
      title: `${sample.id} ${WGBS_DESCRIPTION}`,
      config: {
        urls: {
          plusStrand: {
            cpg: channelUrl(METHYLC_CHANNEL_MARKERS.plusStrand.cpg),
            chg: channelUrl(METHYLC_CHANNEL_MARKERS.plusStrand.chg),
            chh: channelUrl(METHYLC_CHANNEL_MARKERS.plusStrand.chh),
            depth: channelUrl(METHYLC_CHANNEL_MARKERS.plusStrand.depth),
          },
          minusStrand: {
            cpg: channelUrl(METHYLC_CHANNEL_MARKERS.minusStrand.cpg),
            chg: channelUrl(METHYLC_CHANNEL_MARKERS.minusStrand.chg),
            chh: channelUrl(METHYLC_CHANNEL_MARKERS.minusStrand.chh),
            depth: channelUrl(METHYLC_CHANNEL_MARKERS.minusStrand.depth),
          },
        },
        colors: METHYLC_COLORS,
        maskCpgByCoverage: true,
      },
      metadata: toMetadata(info),
    },
  };
}

function buildOmeTracks(data: MohdOmeData) {
  if (data.ome === "wgbs") {
    return data.samples.map((sample) => createWgbsMethylTrack(data, sample));
  }

  const files = orderFiles(data.ome, data.files);

  return data.samples.flatMap((sample) => files.map((file, index) => createFileTrack(data, sample, file, index)));
}

const MOHD_COLUMNS = [
  { field: "description", label: "Description", width: 320 },
  { field: "trackCategory", label: "Track Type", width: 140 },
  { field: "sampleId", label: "Sample ID", width: 180 },
  { field: "ome", label: "Ome", width: 100 },
  { field: "site", label: "Site", width: 100 },
  { field: "protocol", label: "Protocol", width: 160 },
  { field: "sex", label: "Sex", width: 120 },
  { field: "status", label: "Status", width: 120 },
];

const MOHD_VIEWS = [
  {
    id: "ome",
    label: "Ome",
    columns: MOHD_COLUMNS,
    grouping: ["ome", "site", "sampleId"],
    leaf: "description",
  },
  {
    id: "site",
    label: "Site",
    columns: MOHD_COLUMNS,
    grouping: ["site", "ome", "sampleId"],
    leaf: "description",
  },
];

export type MohdCatalog = {
  collection: TrackSelectCollection;
  /** Qualified track ID -> sort metadata, for host-side track ordering. */
  trackInfoById: Map<string, MohdTrackInfo>;
};

/**
 * Build the MOHD collection, optionally restricted to a single ome so a
 * per-ome browser tab only offers that ome's experiments. Filtering happens
 * before tracks are built, so a per-ome browser never constructs the other
 * omes' several thousand track objects.
 */
export function createMohdCatalog(ome?: MohdOme): MohdCatalog {
  const built = MOHD_OME_DATA.filter((data) => !ome || getMohdOmeConfig(data.ome).label === ome).flatMap(
    buildOmeTracks
  );

  return {
    collection: {
      id: MOHD_COLLECTION_ID,
      label: "MOHD",
      description: "Public MOHD signal, methylation, and annotation tracks.",
      views: MOHD_VIEWS,
      tracks: built.map(({ track }) => track),
    },
    trackInfoById: new Map(built.map(({ info }) => [info.id, info])),
  };
}
