"use client";
import { useWGBSData } from "@/common/hooks/omeHooks/useWGBSData";
import { useOmeDownloadFiles } from "@/common/hooks/useOmeDownloadFiles";
import { useMemo, useState, useCallback, ReactNode } from "react";
import { MultiSelectOnChange } from "./MultiSelect";
import { Table, TableColDef } from "@weng-lab/ui-components";
import { GRID_CHECKBOX_SELECTION_COL_DEF, getGridSingleSelectOperators, GridFilterItem, GridFilterModel, GridRowParams, isAutogeneratedRow } from "@mui/x-data-grid-premium";
import { formatBytes } from "@/common/downloads";
import { OmeEnum } from "@/common/types/generated/graphql";
import { IconButton, Tooltip, Box, Checkbox, FormControlLabel, FormGroup, FormLabel } from "@mui/material";
import { Download } from "@mui/icons-material";
import Image from "next/image";
import MultiSelect from "./MultiSelect";

const customSingleSelectOperators = getGridSingleSelectOperators().map((op) =>
  op.value === "isAnyOf"
    ? {
        ...op,
        getApplyFilterFn: (filterItem: GridFilterItem) => {
          if (!Array.isArray(filterItem.value)) return null;
          if (filterItem.value.length === 0) return () => false;
          const filterValues = filterItem.value as string[];
          return (value: string) => filterValues.includes(value);
        },
      }
    : op
);

const CHECKBOX_FIELDS = new Set<FilterField>(["sex", "status"]);
const FILTER_FIELDS = ["file_type", "site", "sex", "status"] as const;
type FilterField = typeof FILTER_FIELDS[number];
const FILTER_LABELS: Record<FilterField, string> = {
  file_type: "File Type",
  site: "Site",
  sex: "Sex",
  status: "Status",
};

const makeColumns = <
  T extends {
    open_access?: boolean | null;
    sample_id: string | null;
    filename: string;
  },
>(
  ome: OmeEnum,
): TableColDef<T>[] => [
  {
    ...GRID_CHECKBOX_SELECTION_COL_DEF,
    renderHeader: (params) => {
      const HeaderCheckbox = GRID_CHECKBOX_SELECTION_COL_DEF.renderHeader;
      if (!HeaderCheckbox) return null;
      return (
        <div>
          <HeaderCheckbox {...params} />
          Bulk Download
        </div>
      );
    },
    renderCell: (params) => {
      const RowCheckbox = GRID_CHECKBOX_SELECTION_COL_DEF.renderCell;
      if (!RowCheckbox) return null;
      const isSelectable = params.api.isRowSelectable(params.id);
      if (!isSelectable) {
        return (
          <Tooltip title={"Not available for bulk download"}>
            <span>
              <RowCheckbox {...params} />
            </span>
          </Tooltip>
        );
      }
      return <RowCheckbox {...params} />;
    },
    minWidth: 150,
  },
  {
    field: "sample_id",
    headerName: "Dataset",
    minWidth: 150,
  },
  {
    field: "site",
    headerName: "Site",
  },
  {
    field: "status",
    headerName: "Status",
  },
  {
    field: "sex",
    headerName: "Sex",
  },
  {
    field: "file_type",
    headerName: "File Type",
    minWidth: 150,
  },
  {
    field: "filename",
    headerName: "Filename",
  },
  {
    field: "size",
    headerName: "File Size",
    valueFormatter: formatBytes,
    align: "right",
  },
  {
    field: "download",
    headerName: "Download",
    sortable: false,
    renderCell: (params) => {
      const index =
        ome === OmeEnum.AtacSeq ? 2 : ome === OmeEnum.RnaSeq ? 3 : 1;

      const { open_access, sample_id, filename } = params.row;
      const url = `https://downloads.mohdconsortium.org/${index}_${ome.replace("-seq", "")}/${sample_id}/${filename}`;

      if (params.rowNode.type === "group") return null;

      if (!open_access) {
        return (
          <IconButton
            component="a"
            href="https://anvilproject.org/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/logo-mark-Anvil.png"
              alt="AnVIL"
              width={28}
              height={28}
            />
          </IconButton>
        );
      }

      return (
        <IconButton component="a" href={url} download color="primary">
          <Download />
        </IconButton>
      );
    },
  },
];

  const ControlLabelWrapper = ({field, children}: {field: FilterField, children: ReactNode}) => (
    <Box key={field}>
      <FormLabel>{FILTER_LABELS[field]}</FormLabel>
      {children}
    </Box>
  );

const WGBSDownloads = () => {

    const {data: dataWGBS, loading: loadingWGBS, error: errorWGBGS } = useWGBSData({ skip: false });
    const { data: dataFileInfo, loading: loadingFileInfo, error: errorFileInfo } = useOmeDownloadFiles(OmeEnum.Wgbs);

    /**
     * Why are rows and downloadFiles not combined right here immediately
     */
    const loading = loadingWGBS || loadingFileInfo
    const error = !!(errorWGBGS || errorFileInfo);

    //Is there some way to not filter out the compressed file for each participant?
    const metadataMap = useMemo(() => {
        if (!dataWGBS) return null
        else return new Map(dataWGBS.map(x => [x.sample_id, x]))
    }, [dataWGBS])

    const files = useMemo(() => {
      if (!metadataMap || !dataFileInfo) return [];
      return dataFileInfo.map((file) => {
        
        // remove __typename by destructuring to allow ts to infer it's removal (delete doesn't)
        /* eslint-disable @typescript-eslint/no-unused-vars */
        const { __typename: _, ...metadata } = metadataMap.get(file.sample_id) ?? {};
        const { __typename: __, ...fileInfo} = file
        /* eslint-enable @typescript-eslint/no-unused-vars */

        return {
          ...fileInfo,
          ...metadata,
          sample_id: file.sample_id.includes("_allsamples")
            ? null
            : file.sample_id,
        };
      });
    }, [metadataMap, dataFileInfo]);

    const optionsMap: Record<string, string[]> = useMemo(() => {
      const uniqueValues = (key: string): string[] => {
        const values = files.map(x => x[key as keyof typeof x]);
        const options = [...new Set(values.filter(Boolean))] as string[]
        return options;
      };
      
      return {
        file_type: uniqueValues("file_type"),
        site: uniqueValues("site"),
        sex: uniqueValues("sex"),
        status: uniqueValues("status"),
      };
    }, [files])

    const columnsWithOptions = useMemo(() => {
      return makeColumns<typeof files[number]>(OmeEnum.Wgbs).map(col =>
        col.field in optionsMap
          ? { ...col, type: 'singleSelect' as const, valueOptions: optionsMap[col.field], filterOperators: customSingleSelectOperators }
          : col
      );
    }, [optionsMap]);

    const [filterModel, setFilterModel] = useState<GridFilterModel>({ items: [] });

    const selectedValues: Record<FilterField, string[]> = useMemo(() => {
      const result = {} as Record<FilterField, string[]>;
      for (const field of FILTER_FIELDS) {
        const item = filterModel.items.find((i) => i.field === field);
        if (!item) {
          result[field] = optionsMap[field] ?? [];
        } else if (item.operator === "isAnyOf" && Array.isArray(item.value)) {
          result[field] = item.value;
        } else if (item.operator === "is" && item.value != null) {
          result[field] = [item.value as string];
        } else if (item.operator === "not" && item.value != null) {
          result[field] = (optionsMap[field] ?? []).filter((v) => v !== item.value);
        } else {
          result[field] = optionsMap[field] ?? [];
        }
      }
      return result;
    }, [filterModel, optionsMap]);

    const handleSelectChange = useCallback(
      (field: FilterField): MultiSelectOnChange<string> => (_event, value) => {
        setFilterModel((prev) => {
          const otherItems = prev.items.filter((item) => item.field !== field);
          if (value.length === optionsMap[field].length) {
            return { ...prev, items: otherItems };
          }
          return {
            ...prev,
            items: [...otherItems, { id: `filter-${field}`, field, operator: "isAnyOf", value }],
          };
        });
      },
      [optionsMap]
    );

    const handleCheckboxChange = useCallback(
      (field: FilterField, option: string) => () => {
        setFilterModel((prev) => {
          const otherItems = prev.items.filter((item) => item.field !== field);
          const current = selectedValues[field];
          const next = current.includes(option)
            ? current.filter((v) => v !== option)
            : [...current, option];
          if (next.length === optionsMap[field].length) {
            return { ...prev, items: otherItems };
          }
          return {
            ...prev,
            items: [...otherItems, { id: `filter-${field}`, field, operator: "isAnyOf", value: next }],
          };
        });
      },
      [optionsMap, selectedValues]
    );

    const handleFilterModelChange = useCallback((model: GridFilterModel) => {
      setFilterModel(model);
    }, []);

    return (
      <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
        <Box
          sx={{
            display: "flex",
            flexWrap: "wrap",
            gap: 2,
            alignItems: "top",
            border: theme =>`1px solid ${theme.palette.divider}`,
            borderRadius: 1,
            p: 2
          }}
        >
          {FILTER_FIELDS.filter((field) => !CHECKBOX_FIELDS.has(field)).map(
            (field) => (
              <ControlLabelWrapper key={field} field={field}>
                <MultiSelect
                  limitTags={3}
                  chipMaxWidth={100}
                  options={optionsMap[field]}
                  value={selectedValues[field]}
                  onChange={handleSelectChange(field)}
                  placeholder={FILTER_LABELS[field]}
                />
              </ControlLabelWrapper>
            ),
          )}
          <Box sx={{ display: "flex", flexWrap: "wrap", gap: 2 }}>
            {FILTER_FIELDS.filter((field) => CHECKBOX_FIELDS.has(field)).map(
              (field) => (
                <ControlLabelWrapper key={field} field={field}>
                  <FormGroup row>
                    {optionsMap[field].map((option) => (
                      <FormControlLabel
                        key={option}
                        label={option}
                        control={
                          <Checkbox
                            size="small"
                            checked={selectedValues[field].includes(option)}
                            onChange={handleCheckboxChange(field, option)}
                          />
                        }
                      />
                    ))}
                  </FormGroup>
                </ControlLabelWrapper>
              ),
            )}
          </Box>
        </Box>
        <Table
          rows={files}
          getRowId={(row) => row.filename}
          loading={loading}
          error={error}
          columns={columnsWithOptions}
          filterModel={filterModel}
          onFilterModelChange={handleFilterModelChange}
          divHeight={{ height: 650 }}
          initialState={{
            pinnedColumns: {
              left: [GRID_CHECKBOX_SELECTION_COL_DEF.field],
            },
            rowGrouping: { model: ["sample_id"] },
            sorting: { sortModel: [{ field: "file_type", sort: "asc" }] },
          }}
          checkboxSelection
          isRowSelectable={(params: GridRowParams<(typeof files)[number]>) =>
            isAutogeneratedRow(params.row) ||
            (!!params.row.open_access &&
              params.row.file_type !== "Compressed Tar File")
          }
          keepNonExistentRowsSelected
        />
      </Box>
    );
}

export default WGBSDownloads;