import { Box, Divider, Stack, Typography } from "@mui/material";
import DataExplorer from "./DataExplorer";

export default function ClinicalDataLanding() {
  return (
    <Box width="100%" sx={{ overflowX: "hidden" }}>
      <Box
        width="100%"
        sx={{
          position: "relative",
          overflow: "hidden",
          display: "grid",
          gridTemplateColumns: { xs: "1fr", md: "minmax(0, 7fr) minmax(0, 5fr)" },
          alignItems: "stretch",
          minHeight: { xs: "100dvh", md: "70vh" },
          backgroundImage: "url('/Backgrounds/clinical-landing-bg@4x.png')",
          backgroundRepeat: "no-repeat",
          backgroundPosition: { xs: "35% 20%", md: "top right" },
          backgroundSize: { xs: "180%", md: "contain" },
          backgroundColor: "primary.main",
          "&::before": {
            content: '""',
            position: "absolute",
            inset: 0,
            backgroundColor: "rgba(0, 61, 56, 0.80)",
            display: { xs: "block", md: "none" },
            zIndex: 1,
          },
        }}
        color="white"
      >
        <Stack
          spacing={5}
          sx={{
            position: "relative",
            zIndex: 2,
            justifyContent: { xs: "flex-start", md: "center" },
            px: { xs: 3, sm: 4, md: 8, lg: 10 },
            py: { xs: 4, md: 5 },
            minHeight: { xs: "100dvh", md: "auto" },
          }}
        >
          <Typography variant="h4" fontWeight={600}>
            Clinical and Phenotypic Data
          </Typography>
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              gap: 2,
              maxWidth: 760,
            }}
          >
            <Divider
              sx={{
                borderColor: "rgba(255,255,255,0.22)",
              }}
            />
            <Typography variant="body1">
              Clinical and phenotypic data include demographic characteristics, medical history, medication use,
              laboratory measurements, lifestyle and health behaviors, residential history, and social and structural
              determinants of health. Data are collected through harmonized surveys, clinical assessments, and
              electronic health records across multiple study visits, enabling researchers to investigate how
              biological, environmental, clinical, and social factors interact to influence health and disease. These
              data provide essential context for interpreting the multi-omic measurements generated by the MOHD
              Consortium.
            </Typography>
          </Box>
        </Stack>
      </Box>
      <DataExplorer />
    </Box>
  );
}
